from __future__ import annotations

from .schemas import Playlist, Song


def seed_listings() -> list[Playlist]:
    return [
        Playlist(
            id=1,
            name="Lo-fi Focus Pack",
            creator="Nora",
            genre="Lo-fi",
            price=8,
            song_ids=[1, 3, 4],
            distribution="paid_sale",
            rights_status="verified",
            cover="https://images.unsplash.com/photo-1461784180009-21121b2f204c?auto=format&fit=crop&w=800&q=80",
            markets=["global", "us", "ca", "uk"],
            age_min=16,
            age_max=38,
            quality_score=0.84,
            trend_score=0.72,
        ),
        Playlist(
            id=2,
            name="Afrobeats Party Mix",
            creator="Kane",
            genre="Afrobeats",
            price=12,
            song_ids=[5, 6, 7],
            distribution="paid_sale",
            rights_status="verified",
            cover="https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=800&q=80",
            markets=["ng", "gh", "ke", "za", "global"],
            age_min=16,
            age_max=34,
            quality_score=0.88,
            trend_score=0.9,
        ),
        Playlist(
            id=3,
            name="Latin Heat Weekend",
            creator="Luma",
            genre="Latin",
            price=10,
            song_ids=[8, 9],
            distribution="paid_sale",
            rights_status="verified",
            cover="https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=80",
            markets=["mx", "br", "ar", "es", "us", "global"],
            age_min=16,
            age_max=39,
            quality_score=0.8,
            trend_score=0.78,
        ),
        Playlist(
            id=4,
            name="Focus Piano Essentials",
            creator="Mira",
            genre="Classical",
            price=9,
            song_ids=[2, 10],
            distribution="paid_sale",
            rights_status="verified",
            cover="https://images.unsplash.com/photo-1507838153414-b4b713384a76?auto=format&fit=crop&w=800&q=80",
            markets=["global", "us", "ca", "uk", "de"],
            age_min=22,
            age_max=60,
            quality_score=0.91,
            trend_score=0.54,
        ),
        Playlist(
            id=5,
            name="Global Pop Radar",
            creator="Rae",
            genre="Pop",
            price=11,
            song_ids=[11, 12],
            distribution="paid_sale",
            rights_status="verified",
            cover="https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?auto=format&fit=crop&w=800&q=80",
            markets=["global"],
            age_min=13,
            age_max=42,
            quality_score=0.79,
            trend_score=0.86,
        ),
        Playlist(
            id=6,
            name="Drill & Trap Selection",
            creator="Skye",
            genre="Hip-Hop",
            price=13,
            song_ids=[13, 14],
            distribution="paid_sale",
            rights_status="verified",
            cover="https://images.unsplash.com/photo-1516280030429-27679b3dc9cf?auto=format&fit=crop&w=800&q=80",
            markets=["us", "uk", "fr", "global"],
            age_min=15,
            age_max=33,
            quality_score=0.83,
            trend_score=0.88,
        ),
        Playlist(
            id=7,
            name="Amapiano Sunset",
            creator="Tayo",
            genre="Amapiano",
            price=10,
            song_ids=[15, 16],
            distribution="paid_sale",
            rights_status="verified",
            cover="https://images.unsplash.com/photo-1470229538611-16ba8c7ffbd7?auto=format&fit=crop&w=800&q=80",
            markets=["za", "ng", "ke", "tz", "global"],
            age_min=16,
            age_max=36,
            quality_score=0.86,
            trend_score=0.91,
        ),
        Playlist(
            id=8,
            name="Calm Sleep Waves",
            creator="Arin",
            genre="Ambient",
            price=7,
            song_ids=[17, 18],
            distribution="free_share",
            rights_status="not_required",
            cover="https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=800&q=80",
            markets=["global"],
            age_min=18,
            age_max=65,
            quality_score=0.77,
            trend_score=0.49,
        ),
    ]


def seed_songs() -> list[Song]:
    return [
        Song(id=1, title="Quiet Desk", artist_id="ar_nora", artist_name="Nora", genre="Lo-fi", tier="free", price=0),
        Song(id=2, title="Piano Drift", artist_id="ar_mira", artist_name="Mira", genre="Classical", tier="premium", price=1.49),
        Song(id=3, title="Night Focus", artist_id="ar_nora", artist_name="Nora", genre="Lo-fi", tier="premium", price=1.29),
        Song(id=4, title="Soft Rain Loops", artist_id="ar_arin", artist_name="Arin", genre="Ambient", tier="free", price=0),
        Song(id=5, title="Lagos Bounce", artist_id="ar_kane", artist_name="Kane", genre="Afrobeats", tier="premium", price=1.49),
        Song(id=6, title="Street Heat", artist_id="ar_kane", artist_name="Kane", genre="Afrobeats", tier="premium", price=1.29),
        Song(id=7, title="Palm Sunrise", artist_id="ar_tayo", artist_name="Tayo", genre="Amapiano", tier="free", price=0),
        Song(id=8, title="Rio Nights", artist_id="ar_luma", artist_name="Luma", genre="Latin", tier="premium", price=1.39),
        Song(id=9, title="Carnival Pulse", artist_id="ar_luma", artist_name="Luma", genre="Latin", tier="free", price=0),
        Song(id=10, title="Concert Hall", artist_id="ar_mira", artist_name="Mira", genre="Classical", tier="free", price=0),
        Song(id=11, title="Pop Signal", artist_id="ar_rae", artist_name="Rae", genre="Pop", tier="premium", price=1.19),
        Song(id=12, title="World Anthem", artist_id="ar_rae", artist_name="Rae", genre="Pop", tier="free", price=0),
        Song(id=13, title="City Drill", artist_id="ar_skye", artist_name="Skye", genre="Hip-Hop", tier="premium", price=1.49),
        Song(id=14, title="Trap Echoes", artist_id="ar_skye", artist_name="Skye", genre="Hip-Hop", tier="premium", price=1.49),
        Song(id=15, title="Sunset Keys", artist_id="ar_tayo", artist_name="Tayo", genre="Amapiano", tier="free", price=0),
        Song(id=16, title="Township Steps", artist_id="ar_tayo", artist_name="Tayo", genre="Amapiano", tier="premium", price=1.39),
        Song(id=17, title="Sleep Tide", artist_id="ar_arin", artist_name="Arin", genre="Ambient", tier="free", price=0),
        Song(id=18, title="Deep Calm", artist_id="ar_arin", artist_name="Arin", genre="Ambient", tier="free", price=0),
    ]
